config/routes.rb
Rails.application.routes.draw do
  resources :trackers
  get 'home' => 'trackers#current'
  get 'status' => 'trackers#status'
  get 'delete_all' => 'trackers#remove'
  get 'search' => 'application#search'
  get    '/trackers/:id' => 'trackers#show'
  get 'cleaner' => 'cleaner#testcod'
  post 'cleaner/done' => 'cleaner#posttestcod'#, via:[:get, :post]
  post 'cleaner/raw'=>'cleaner#htmlraw'
  get 'nokocleaner' => 'trackers#testcod'
  post 'nokocleaner/done' => 'trackers#posttestcod'
  get 'pending' => 'trackers#pending_tickets'
  get 'charts' => 'trackers#chart_page'

  resources :users
  get 'signup'  => 'users#new' 
  

  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  root :to => 'sessions#new'

  get 'dashboard'=>'dashboard#index'
  get '/dashboard/outbound' =>'dashboard#outbound' 
  get '/dashboard/neutral' =>'dashboard#neutral'
  get '/dashboard/inbound' =>'dashboard#inbound'
  post '/assign' => 'dashboard#assign'

  get 'news'=>'news#new'
  post '/news/generated'=>'news#news_gen'

get 'test1' =>'cleaner#test'
  

end

app/models/tracker.rb
class Tracker < ActiveRecord::Base

def self.to_csv(options = {})
	CSV.generate(options) do |csv|
		name_array={"Date"=>"created_at","TICKET ID"=>"ticket_id",
			"TICKET OWNER"=>"owner","CREATED"=>"created",
			"ETA"=>"eta","FINISHED"=>"finished","TYPE OF WORK"=>"tow",
			"COMMITS"=>"noc","STAGING"=>"staging",
			"DESCRIPTION"=>"disc","CONFIG OWNER"=>"uid"}
		csv << name_array.keys #column_names
		all.each do |ticket|
			csv << ticket.attributes.values_at(*name_array.values)
		end
	end
end
	
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]

  # GET /trackers
  # GET /trackers.json
  def index
    require_user
    stats=Tracker.where('uid=?',user).pluck("comp")
    @ontime=stats.count("On Time")
    @delay=stats.count("> ETA")
    @early=stats.count("< ETA")
    @trackers = Tracker.where('uid=?',user).order(created_at: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data @trackers.to_csv}
      format.xls# { send_data @trackers.to_csv(col_sep: "\t")}
    end
    
  end

  # def completed_tasks
  # render json: Task.group_by_day(:created_at).count.chart_json
  # end

  def chart_page
    require_user
    a=Time.now 
    my=a.strftime("%-m-%y")

    @pie=Tracker.where('uid=? and created like ?',user, "%#{my}%")
  end

  def current
    require_user
    @tracker = Tracker.new
    @trackers = Tracker.where('uid=? and created_at > ? AND created_at < ?', user, Date.yesterday.beginning_of_day, Date.today.end_of_day).order(created_at: :desc)
    stats=@trackers.pluck("comp")
    @ontime=stats.count("On Time")
    @delay=stats.count("> ETA")
    @early=stats.count("< ETA")
   # Tracker.where("created_at between ? and ?", Date.yesterday.beginning_of_day, Date.today.end_of_day)
  end

def testcod
end

def posttestcod

if params[:accept] == "1"
      path=["//ul/li/p"]
else
      path=["//table/tbody/tr/td/p", "//ul/li/p"]
end

    nogo={'<p> </p>' => '', 
      '<table>' => "\n<table width='100%' border='0' cellspacing='0' cellpadding='0' class='table table-curved'>", 
     '&lt;' => '<', '&gt;'=>'>','<br>' => '','<p></p>' => '', ' rel="nofollow"' => '', "http://www.bankbazaar.com"=>"",
        "https://www.bankbazaar.com"=>"",'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">'=>"",
          "<html><body>"=>"","</body></html>"=>""}  

      
      c=params[:content]
       bundle_out=Sanitize.fragment(c,Sanitize::Config.merge(Sanitize::Config::BASIC,
       :elements=> Sanitize::Config::BASIC[:elements]+['table', 'tbody', 'tr', 'td', 'h1', 'h2', 'h3'],
       :attributes=>{'a' => ['href']}) )

      re = Regexp.new(nogo.keys.map { |x| Regexp.escape(x) }.join('|'))

      puts "re====#{re}"
      intr=bundle_out.gsub(re, nogo)

      doc=Nokogiri::HTML.parse(intr)
      
      path.each do |p|
        puts p
        doc.xpath(p).each do |pp|
          pp.replace(pp.text)
        end
      end
      filter=doc.to_html
      @bundle_out=filter.gsub(re,nogo)


      open_tags= @bundle_out.scan(/</).count
      close_tags= @bundle_out.scan(/<\//).count

      if open_tags/2 == close_tags
        @tags=["Open and close tags are equal"]
      else
        @p=@bundle_out.scan(/<p/).count
        @cp=@bundle_out.scan(/<\/p/).count
        @li=@bundle_out.scan(/<li/).count
        @cli=@bundle_out.scan(/<\/li/).count
        @ul=@bundle_out.scan(/<ul/).count
        @cul=@bundle_out.scan(/<\/ul/).count
        @ol=@bundle_out.scan(/<ol/).count
        @col=@bundle_out.scan(/<\/ol/).count
        @tab=@bundle_out.scan(/<table/).count
        @ctab=@bundle_out.scan(/<\/table/).count
        @tr=@bundle_out.scan(/<tr/).count
        @ctr=@bundle_out.scan(/<\/tr/).count
        @td=@bundle_out.scan(/<td/).count
        @ctd=@bundle_out.scan(/<\/td/).count

        arr=[[@li,@cli,'li'],[@ul,@cul,'ul'],[@ol,@col,'ol'],[@p,@cp,'p'],[@tab,@ctab,'table'],[@tr,@ctr,'tr'],[@td,@ctd,'td']]
        bar=[] #initializing empty array to appand the results
        for i in 0..arr.count-1
        if arr[i][0] != arr[i][1]
        var=arr[i][2]+"="+arr[i][0].to_s+"|"+arr[i][1].to_s
        @error=bar<<var
        end
        end
        @tags=@error
        end
end



  def status
    require_user
      @date = params[:month] ? Date.parse(params[:month]) : Date.today
      my=@date.strftime("%-m-%y")
      puts my
      # @dat = Tracker.where('created_at > ? AND created_at < ?', @date.beginning_of_day, @date.end_of_month.end_of_day)
      @dat=Tracker.where("uid=? and finished LIKE ? or finished Like ?", user, "%#{my}%", "#{@date.strftime("%m/%y")}").order(created_at: :asc)
      stats=@dat.pluck("comp")
      @this_month_neutral=stats.count("On Time")
      @this_month_delay=stats.count("> ETA")
      @this_month_early=stats.count("< ETA")
      @pen= Tracker.where("uid=? and finished=?",user, "")
      @trackers = Tracker.where("uid=?",user)
    stats=@trackers.pluck("comp")
    @ontime=stats.count("On Time")
    @delay=stats.count("> ETA")
    @early=stats.count("< ETA")

    respond_to do |format|
      format.html
      format.csv { send_data @dat.to_csv}
      format.xls# { send_data @trackers.to_csv(col_sep: "\t")}
    end

  end

  def pending_tickets
    @trackers=Tracker.where("uid=? and finished=?",user, "")
  end
    # GET /trackers/1
  # GET /trackers/1.json
  def show
    
  end

  # GET /trackers/new
  # def new
  #   @tracker = Tracker.new
  #   redirect_to '/trackers'
  # end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to '/home', notice: 'Ticket was added successfully.' }
        format.json { render :index, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
    completed
  end

def completed
  @com=Tracker.where("id=?",params[:id]).pluck("finished").last
  if @com != ""
    @eta=Tracker.where("id=?",params[:id]).pluck("eta").last
    @a=Date.parse(@eta)
    @b=Date.parse(@com)
        @c=(@a-@b).to_i
    if @c>0
      @complt="< ETA"
    elsif @c==0
      @complt="On Time"
    elsif @c<0
      @complt="> ETA"
    end
    puts "oooo====#{@complt}"
@tracker.update(:comp => @complt) 
end
end


  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove
    require_admin
    Tracker.delete_all
    redirect_to '/home'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:ticket_id, :comp, :staging, :created, :eta, :finished, :tow, :owner, :noc, :disc, :uid)
    end

end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/_dtable.html.erb
<%#= render :partial => "/trackers/form.html.erb"%>

<h1 style="text-align:center;">Pending Tickets</h1>

<div class="pull-left"><span>Pending:</span> <%=pending%></div>



<div style="clear:both"></div>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="2">Ticket ID</th>
      <th>Ticket Owner</th>
      <th>Created</th>
      <th>ETA</th>
      <th>Finished</th>
      <th>Type of Work</th>
      <th>No. of Commits</th>
      <th>Staging</th>
    <!--   <th>Completed</th> -->
      <th>Description</th>
      <th>Blurb</th>
      <th>Delete</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.created_at.strftime("%d-%m-%y")%></td>
        <td ><%= best_in_place tracker, :ticket_id, :inner_class => "tdfield" %><td width="20px;">   <a target="_blank" href="https://bankbazaarmail.zendesk.com/agent/tickets/<%= tracker.ticket_id%>">Open</a></td></td>
        <td ><%= best_in_place tracker, :owner, :inner_class => "tdfield" %></td>
                  <td ><%= best_in_place tracker, :created, :inner_class => "tdfield" %></td>
        <td ><%= best_in_place tracker, :eta, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :finished, :inner_class => "tdfield"%></td>
        <td ><%=  best_in_place tracker, :tow, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :noc, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :staging, :inner_class => "tdfield"%></td>
        <!-- <td ><%= tracker.comp %></td> -->
        <td ><%= best_in_place tracker, :disc, :as => :textarea%></td>
        <td><%= link_to 'Show', tracker %></td>
        <!-- <td><%#= link_to 'Edit', edit_tracker_path(tracker) %></td> -->
        <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/_form.html.erb
<%= form_for(@tracker) do |f| %>
  <% if @tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% @tracker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Ticket_id %><br>
    <%= f.number_field :ticket_id, class: "one" %>
  </div>
  <div class="field">
    <%= f.label :Created %><br>
    <%= f.text_field :created, class: "one" %>
  </div>
  <div class="field">
    <%= f.label :ETA %><br>
    <%= f.text_field :eta, class: "one" %>
  </div>
  <div class="field">
    <%= f.label :Finished %><br>
    <%= f.text_field :finished, class: "one" %>
  </div>
  <div class="field">
    <%= f.label :Ticket_Owner %><br>
    <%= f.text_field :owner, class: "one"%>
  </div>
  <div class="field">
    <%= f.label :Type_of_work %><br>
    <%#= f.text_field :tow, class: "one"%>
    <%=f.select :tow, options_for_work,{}, class: "one"%>
  </div>
  <div class="field">
    <%= f.label :Num_of_Commits %><br>
    <%= f.number_field :noc, class: "one"%>
  </div>
  <div class="field">
    <%= f.label :Staging %><br>
    <%= f.text_field :staging, class: "one"%>
  </div>
  
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :disc, class: "one"%>
  </div>

  <div class="field">
    <%= f.hidden_field :uid, :value => current_user.id, class: "one"%>
  </div>
  <div style="clear:both"></div>
  <div class="actions">
    <%= f.submit "Save"%>
  </div>
<% end %>

app/views/trackers/chart_page.html.erb
<div>
	<p style="text-align:center; font-weight:bold">LINE CHART FOR CURRENT MONTH</p>
<%= line_chart Tracker.where("uid=?",current_user.id).group_by_day(:created_at).count, xtitle: "Date", ytitle: "No. of Tickets"%> 
</div>

<div>
	<p style="text-align:center; font-weight:bold">PIE CHART FOR CURRENT MONTH</p>
<%= pie_chart @pie.group(:tow).count%>
</div>

app/views/trackers/cleaner.html.erb
<%= form_tag url_for(:controller=>"trackers",:action =>"htmlclnr")  do %>
	<%= tinymce_assets %>

<%= text_area_tag :content, "", :class => "tinymce", :rows => 20, :cols => 120 %>

<%= tinymce %>
 <%= submit_tag 'Bundle', :disable_with => 'Please wait...'%>
	<%end%>

app/views/trackers/current.html.erb
<%= render :partial => "/trackers/form.html.erb"%>
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;">Recent Tickets</h1>

<div class="pull-left"><span>Pending:</span> <%=pending%></div>

<div class="status"><span>Outbound:</span> <%=@delay%></div>

<div class="status"><span>Neutral:</span> <%=@ontime%></div>

<div class="status"><span>Inbound:</span> <%=@early%></div>


<div style="clear:both"></div>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="2">Ticket ID</th>
      <th>Ticket Owner</th>
      <th>Created</th>
      <th>ETA</th>
      <th>Finished</th>
      <th>Type of Work</th>
      <th>No. of Commits</th>
      <th>Staging</th>
      <th>Completed</th>
      <th>Description</th>
      <th>Blurb</th>
     <!--  <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%=tracker.created_at.strftime("%d-%m-%y")%></td>
        <td ><%= best_in_place tracker, :ticket_id, :inner_class => "tdfield"%><td width="20px;">   <a target="_blank" href="https://bankbazaarmail.zendesk.com/agent/tickets/<%= tracker.ticket_id%>">Open</a></td></td>
        <td ><%= best_in_place tracker, :owner, :inner_class => "tdfield" %></td>
                  <td ><%= best_in_place tracker, :created, :inner_class => "tdfield" %></td>
        <td ><%= best_in_place tracker, :eta, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :finished, :inner_class => "tdfield"%></td>
        <td ><%=  best_in_place tracker, :tow, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :noc, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :staging, :inner_class => "tdfield"%></td>
        <td ><%= tracker.comp %></td>
        <td ><%= best_in_place tracker, :disc, :as => :textarea%></td>
        <td><%= link_to 'Show', tracker %></td>
              <!-- <td><%#= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trackers/edit.html.erb
<h1>Editing Tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/htmlclnr.html.erb
<%#= form_tag url_for(:controller=>"trackers",:action =>"htmlclnr") ,:method=>"get" do %>
	<!--<extarea style="width:800px; height:200px;" name="content" ></textarea>-->
	 <%#= submit_tag 'Bundle'%>
	<%#end%>

	
<%if @onestep != nil%>
<textarea style="width:1200px; height:800px;">

	<% @onestep.each do |tagged|%>
	<%=tagged.attribute("textContent").split(" ").join(" ")%>
	<%end%>
</textarea>
<%end%>

app/views/trackers/index.html.erb
<%#= render :partial => "/trackers/form.html.erb"%>
<p id="notice"><%= notice %></p>



<h1 style="text-align:center;">All Tickets</h1>
<h5 style="text-align:center;">Export:
  <%= link_to "CSV", trackers_path(format: "csv") %> |
  <%= link_to "Excel", trackers_path(format: "xls") %></h5>

<div class="pull-left"><span>Total:</span> <%=@trackers.count%></div>
<div class="pull-left"><span>Pending:</span> <a href="/pending"><%=pending%></a></div>


<div class="status"><span>Outbound:</span> <%=@delay%></div>

<div class="status"><span>Neutral:</span> <%=@ontime%></div>

<div class="status"><span>Inbound:</span> <%=@early%></div>

<div style="clear:both"></div>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="2">Ticket ID</th>
      <th>Ticket Owner</th>
      <th>Created</th>
      <th>ETA</th>
      <th>Finished</th>
      <th>Type of Work</th>
      <th>No. of Commits</th>
      <th>Staging</th>
    <!--   <th>Completed</th> -->
      <th>Description</th>
      <th>Blurb</th>
      <th>Delete</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.created_at.strftime("%d-%m-%y")%></td>
        <td ><%= best_in_place tracker, :ticket_id, :inner_class => "tdfield" %><td width="20px;">   <a target="_blank" href="https://bankbazaarmail.zendesk.com/agent/tickets/<%= tracker.ticket_id%>">Open</a></td></td>
        <td ><%= best_in_place tracker, :owner, :inner_class => "tdfield" %></td>
                  <td ><%= best_in_place tracker, :created, :inner_class => "tdfield" %></td>
        <td ><%= best_in_place tracker, :eta, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :finished, :inner_class => "tdfield"%></td>
        <td ><%=  best_in_place tracker, :tow, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :noc, :inner_class => "tdfield"%></td>
        <td ><%= best_in_place tracker, :staging, :inner_class => "tdfield"%></td>
        <!-- <td ><%= tracker.comp %></td> -->
        <td ><%= best_in_place tracker, :disc, :as => :textarea%></td>
        <td><%= link_to 'Show', tracker %></td>
        <!-- <td><%#= link_to 'Edit', edit_tracker_path(tracker) %></td> -->
        <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Tickets">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">DATE</Data></Cell>
        <Cell><Data ss:Type="String">TICKET ID</Data></Cell>
        <Cell><Data ss:Type="String">TICKET OWNER</Data></Cell>
        <Cell><Data ss:Type="String">CREATED</Data></Cell>
        <Cell><Data ss:Type="String">ETA</Data></Cell>
        <Cell><Data ss:Type="String">FINISHED</Data></Cell>
        <Cell><Data ss:Type="String">TYPE OF WORK</Data></Cell>
        <Cell><Data ss:Type="String">COMMITS</Data></Cell>
        <Cell><Data ss:Type="String">STAGING</Data></Cell>
        <Cell><Data ss:Type="String">DESCRIPTION</Data></Cell>
        <Cell><Data ss:Type="String">CONFIG OWNER</Data></Cell>
      </Row>
    <% @trackers.each do |tracker| %>
      <Row>
        <Cell><Data ss:Type="String"><%= tracker.created_at.strftime("%d-%m-%y") %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= tracker.ticket_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.owner %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.created %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.eta %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.finished %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.tow %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= tracker.noc %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.staging %></Data></Cell>
        <Cell><Data ss:Type="String"><%= tracker.disc %></Data></Cell>
        <Cell><Data ss:Type="String"><%= current_user.name.capitalize %></Data></Cell> 
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/trackers/new.html.erb
<h1>New Tracker</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/pending_tickets.html.erb
<%= render 'dtable' %>

app/views/trackers/posttestcod.html.erb
<script>
function goBack() {
    window.history.back();
}
</script>

<!-- <div class="comments">
	<%#if @tags != nil%>
	<%=@tags%>
	<%#else%>
	<span>&lt;p&gt;/&lt;/p&gt; - <%=@p%>/<%=@cp%></span>
	<span>&lt;li&gt;/&lt;/li&gt; - <%=@li%>/<%=@cli%></span>
	<span>&lt;ol&gt;/&lt;/ol&gt; - <%=@ol%>/<%=@col%></span>
	<span>&lt;ul&gt;/&lt;/ul&gt; - <%=@ul%>/<%=@cul%></span>
	<span>&lt;table&gt;/&lt;/table&gt; - <%=@tab%>/<%=@tab%></span>
	<span>&lt;tr&gt;/&lt;/tr&gt; - <%=@tr%>/<%=@ctr%></span>
	<span>&lt;td&gt;/&lt;/td&gt; - <%=@td%>/<%=@ctd%></span>
	<%#end%>
</div> -->

<div class="comments">
	<%@tags.each do |tag|%>
	<%=tag%>
	<%end%>
</div>
<div class="half-one">
	<button onclick="goBack()", class="btn-submit">Go Back  </button> <br><br>
<textarea id="textarea2" style="width:100%; height:493px;"><%=@bundle_out%></textarea>
<button onclick="goBack()", class="btn-submit">Go Back</button>
</div>

app/views/trackers/show.html.erb
<p>
  <strong>Pull Request:</strong><br>
  <textarea style="height:100px; width:900px;">Hi Raji,

Please pull the staging candidate group "<%= @tracker.staging %>" for changes done in gamma.</textarea>
</p>


<p>
  <strong>Live:</strong><br>
  <textarea style="height:100px; width:500px;">Hi <%= @tracker.owner %>,

Changes are live in Production.</textarea>
</p>

app/views/trackers/testcod.html.erb
<!--<%#= form_tag url_for(:controller=>"trackers",:action =>"posttestcod")  do %>
<%#= form_tag url_for(:controller=>"trackers",:action =>"testcod", remote: true) ,:method=>"post" do %>
	<textarea contenteditable='true', style="width:800px; height:200px;" name="content" ></textarea>
	 <%#= submit_tag 'Bundle', :disable_with => 'Please wait...'%>
	<%#end%>


<div id="category">
  <%#=render 'output'%>
</div>-->

<div class="half-one">
	
<%= form_tag url_for(:controller=>"trackers",:action =>"posttestcod")  do %>
<%= check_box_tag 'accept'%>
<%= label_tag(:allowed, "Allow <p> inside <td>") %>
<%= tinymce_assets %>

<%= text_area_tag :content, "", :class => "tinymce", :rows => 28, :cols => 10 %>

<%= tinymce %>
 <%= submit_tag 'Clean', class: "btn-submit"%>
	<%end%>
</div>